FROM registry.gitlab.com/imagelint/imagelint:docker-base-v1.7

RUN sed -i "/;opcache.validate_timestamps=1/copcache.validate_timestamps=0" /etc/php/7.4/fpm/php.ini && \
    sed -i "/;opcache.enable=1/copcache.enable=1" /etc/php/7.4/fpm/php.ini

# Copy our files
COPY . /var/www/html

RUN ln -s /var/www/html/storage/app/public /var/www/html/public/storage

RUN composer install
