#!/usr/bin/env bash

# Run PHP-FPM as current user
if [ ! -z "$WWWUSER" ]; then
    sed -i "s/user\ \=.*/user\ \= $WWWUSER/g" /etc/php/7.4/fpm/pool.d/www.conf

    # Set UID of user "imagelint"
    usermod -u $WWWUSER imagelint
fi

# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

# Run a command or supervisord
if [ $# -gt 0 ];then
    # If we passed a command, run it as current user
    exec gosu $WWWUSER "$@"
else
    # Otherwise start supervisord
    /usr/bin/supervisord
fi
