version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: imagelint/app
    ports:
      - "80:80"
    volumes:
     - .:/var/www/html:cached
     - ./vendor:/var/www/html/vendor:delegated
     - ./docker/app/nginx.conf:/opt/nginx/conf/nginx.conf
    environment:
      DB_HOST: "mysql"
      DB_PASSWORD: "secret"
      DB_DATABASE: "imagelint"
      DB_USERNAME: "homestead"
      DB_PORT: "3306"
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:6
  mysql:
    image: mysql:8
    ports:
     - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "imagelint"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - imagelintmysql:/var/lib/mysql
volumes:
  imagelintmysql:
    driver: "local"
