version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: imagelint/app
    ports:
      - "80:80"
    volumes:
     - .:/var/www/html:cached
     - ./vendor:/var/www/html/vendor:delegated
    depends_on:
      - redis
      - mysql
      - syslogng
    networks:
     - imagelint
  redis:
    image: redis:6
    networks:
      - imagelint
  syslogng:
    build:
      context: ./docker/syslog-ng
      dockerfile: Dockerfile
    image: imagelint/syslog-ng
    volumes:
      - ./syslog-ng/logs:/var/log
      - ./docker/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    cap_add:
      - ALL
    networks:
      - imagelint
    depends_on:
      - mysql
    environment:
      DB_HOST: "mysql"
      DB_PASSWORD: "secret"
      DB_DATABASE: "imagelint"
      DB_USERNAME: "homestead"
      DB_PORT: "3306"
  mysql:
    image: mysql:8
    ports:
     - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "imagelint"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - imagelintmysql:/var/lib/mysql
    networks:
     - imagelint
networks:
  imagelint:
    driver: "bridge"
volumes:
  imagelintmysql:
    driver: "local"
