name: ci

on:
  push:
    branches: feature/add-actions

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Gitlab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: gitlab+deploy-token-252998
          password: ${{ secrets.GITLAB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.gitlab.com/imagelint/imagelint:test
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
